name: Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  run-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Create venv
        run: |
          python -m venv ./venv
          source ./venv/bin/activate
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install build
      - name: Run tests
        run: python -m unittest
      - name: Generate module
        run: python -m build
      - name: Generate release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.tar.gz
            dist/*.whl
