name: Tests
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Create venv
        run: |
          python -m venv ./venv
          source ./venv/bin/activate
      - name: Install requirements.txt
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest

  export-artifacts:
    runs-on: ubuntu-22.04
    needs: [run-tests]
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Create venv
        run: |
          python -m venv ./venv
          source ./venv/bin/activate
      - name: Install requirements.txt
        run: |
        pip install -r requirements.txt
        pip install build
      - name: Generate module files
        run: python -m build
      - name: Export artifacts
        uses: actions/upload-artifact@v3
        with:
          name: module.zip
          path: dist/